[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "s1_sol"
version = "0.1.0"
description = "Solution for the S1 coursework 2025/26"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Harvey Bermingham", email = "hb747@cam.ac.uk" }
]

#setting dependencies
dependencies = [
    "numpy",
    "matplotlib",
    "requests",
    "scipy",
    "pandas",
    "iminuit"
]
requires-python = ">=3.9"

[tool.setuptools]
packages = ["s1_sol"]

[tool.setuptools.package-data]
s1_sol = ["*.mplstyle"]
